### ISSUE TITLE
Recent activity- Shows , [username] has been assigned as camp leader, but 'Sign ' functionality is not implemented

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1086]
![Screenshot 2024-08-05 at 10 19 32 PM](https://github.com/user-attachments/assets/8ac5fd4f-4523-439d-8d7f-9d82bd89d501)

**Comment by array-junkie** [comment]
@saniatg This issue occurred because camp leader functionality was not merged then. Camp leader functionality is incorporated and it should work as expected. Kindly take a look and if any bug is found, report me.

![Image](https://github.com/user-attachments/assets/76b7f096-a895-4e71-9254-a1a07a9e42fd)

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
