### ISSUE TITLE
Remove subscription from entire topic not working

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1142]
Steps:

1. Click on the remove icon
2. Click 'remove ' on confirmation pop up

Nothing is happening
![Screenshot 2024-08-27 at 10 48 29 AM](https://github.com/user-attachments/assets/aeb11922-545c-4032-bbfc-8cd7b17880ec)

**Comment by ks-rahul** [comment]
@saniatg Both topics and camps are currently subscribed. When 'Remove Subscription' is selected for a topic, the subscription is removed only from that topic, while the item remains in the list due to the camp subscription. The system is designed to manage subscriptions for camps and topics independently, meaning that unsubscribing from a topic does not affect the camp subscription.

**Comment by saniatg** [comment]
verified
