### ISSUE TITLE
In the scenario shown below, the thread page displays invalid dates while hovering over the agreement camp. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1254]
Steps to reproduce : 
1. Create topic 
2. Go to topic or camp history
3. Click on view this version
4. Click on Start a thread 
5. Observe bred crumb 

Please refer below screenshot : 
![image](https://github.com/user-attachments/assets/0d64e00d-218b-437a-83ae-dad0de213247)

**Comment by rupalichavan9860** [comment]
Submitter and camp leader name is also missing 
Single level camps only and Disable additional sub camps values are also incorrect

**Comment by sajid315** [comment]
I just checked this issue on call with @rupalichavan9860, so the issue identified is actually due to format of date going from front-end to back-end in `get-camp-record` api. 
Right now its plain text as epoch but in other places its going after conversion.

It should be like this 

![Image](https://github.com/user-attachments/assets/a68ded85-a85c-41aa-8b4a-d6a417e928ce)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2227

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
