### ISSUE TITLE
Issues on Videos page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1391]
Issue 1 : While a user is on a video link at the bottom, the scroll bar returns to the top. 

![image](https://github.com/user-attachments/assets/50a43bc0-b083-4ddc-9c0b-63ba5402c86e)

Issue 2 : Few links seem like normal text; they should be colored blue.
![image](https://github.com/user-attachments/assets/61b588b8-cd66-4216-8e4e-45d7e4022227)

**Comment by DevAlchemyCD** [comment]
As per the discussion with @rahul, about reloading the video page on each click. This issue is due to a redirection wrapper applied to the application to redirect users back to the same page after authentications. 
Regarding that wrapper issue, @rahul is looking into this in the ticket 
(https://github.com/the-canonizer/canonizer-3.0-frontend/issues/2206) and I am verifying the issue in terms of cache and debugging. 

The issue regarding link color for VTT files has been resolved.

**Comment by sajid315** [comment]
This issue has been fixed under below commit link: 
https://github.com/the-canonizer/canonizer-3.0-frontend/commit/3de0a3fa06985c2f4cd88dfafe535d666a05db3c

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rahul** [comment]
> As per the discussion with @rahul, about reloading the video page on each click. This issue is due to a redirection wrapper applied to the application to redirect users back to the same page after authentications. Regarding that wrapper issue, @rahul is looking into this in the ticket ([the-canonizer/canonizer-3.0-frontend#2206](https://github.com/the-canonizer/canonizer-3.0-frontend/issues/2206)) and I am verifying the issue in terms of cache and debugging.
> 
> The issue regarding link color for VTT files has been resolved.

I think you have tagged the wrong @rahul here :)

**Comment by rupalichavan9860** [comment]
Verified on live
