### ISSUE TITLE
Topic name link from below email should highlight Topic name/Agreement camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#14]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/203487734-31769f1a-f2fd-4782-9fae-e3f8a57d1c55.png)

Expected Result : Topic name link should highlight Topic name/Agreement camp

Actual Result : Link is highlighting sub camp

**Comment by nalwa** [comment]
@rupalichavan9860  as per  my understanding this is not the issue. i have given link of **First Choice of support** of direct supporter under the topic. 

Because if i will give link to Agreement camp then delegate supporter won't be able to see direct supporter and their own delegates support under the **Support Tree.** 

That's why whatever is first choice of direct supporter this link will lead to that camp only, and if i my memory serves me right @BrentAllsop  also mentioned the same in  one of the issue in canonizer 2.O. 

To verify we can discuss this with @BrentAllsop  again.
