### ISSUE TITLE
Not able to create new camp with similar name for old topics

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1413]
Steps:
Select any old topic
Try to create a camp under it with similar name like "c1"
Click on create camp
Contribute pop appear
Click on "continue creating new camp" button
Observe result :  It remains on topic detail page after click on "continue creating new camp" instead of creating a new camp for this topic
![Image](https://github.com/user-attachments/assets/a0c9ab19-753a-479d-9228-fe0bf0ec76c7)

**Comment by sajid315** [comment]
@hassaanCD I just checked your point , its not the actual issue. 

Because user can not create same name camp in a topic, so in above topic you mentioned C1 already exists. And we have a message for users as below,

![image](https://github.com/user-attachments/assets/00e1e7c8-1664-45f8-b021-dd90f6693fbd)

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
