### ISSUE TITLE
Camp History Comparison : Objected camp name showing for parent camp field

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1505]
Please refer attached screenshot : 

Camp History Comparison Page : 
![image](https://github.com/user-attachments/assets/48c5146b-c475-4be7-a633-931ec9f5e98f)

Parent Camp History page : 
![image](https://github.com/user-attachments/assets/dbc79f33-896d-4a18-b913-2d75c2092d8c)

**Comment by DevAlchemyCD** [comment]
Although issue has been identified and also exist for older system as well attached in screenshot. 
So as discussed with @rupalichavan9860 we need to show the latest camp name in comparison. 

@sajid315 ! some changes are required on the backend side as well,  because the results are coming from API.

![Image](https://github.com/user-attachments/assets/295ae92b-f121-43c8-becc-07be8e70d2cd)

**Comment by sajid315** [comment]
PR Raised and merged in Iteration 6:
https://github.com/the-canonizer/canonizer-3.0-api/pull/1189

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
