### ISSUE TITLE
Enable/disable button for push notification  is not working smoothly

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#196]
It is not turning ON 
And if ON it is not turning OFF
![Screenshot 2023-02-28 at 11 56 19 AM](https://user-images.githubusercontent.com/91254708/221775232-782112db-5669-4397-b2fe-2fbb6e87820d.png)

**Comment by ks-rahul** [comment]
Hi @saniatg this issue was already discussed with @rupalichavan9860 some time ago. this thing happens because the browser provides the token for notification that takes time and we can't control this. we can only add a spinner or some test like **"Please wait"**. 

@rupalichavan9860  @saniatg please suggest.

**Comment by rupalichavan9860** [comment]
Working well with a spinner

**Comment by rupalichavan9860** [comment]
Verified on live
