### ISSUE TITLE
Parent change issue

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#230]
Steps to reproduce : 
1. Login with User A and create topic
2. Create 3 camps "Camp 1", "Camp 2", "Camp 3"
3. Support all 3 camps
4. Login with User B 
5. Change parent of "Camp 2" to "Camp 3" from Agreement 
6. Change parent of "Camp 1" to "Camp 2" from Agreement
7. Apply include review and observe tree ,

![image](https://user-images.githubusercontent.com/40416610/227313410-5b76d54f-648a-434e-b93b-a6a38cd1b98f.png)

8. Change parent of "Camp 3" to "Camp 1"  (This is an issue ,"Camp 1" should not list under parent camp because "Camp1" will be child camp of "Camp 3" once change will get approve)

![image](https://user-images.githubusercontent.com/40416610/227313672-628367c3-7822-4e46-b795-59905f099eaa.png)

After step 8 when user submits the change and apply "include review" , tree is blank 

![image](https://user-images.githubusercontent.com/40416610/227314935-d2ce68ad-5e5a-403b-9b7d-39053e7a66c9.png)

**Comment by nalwa** [comment]
@rupalichavan9860  as per discussion we are displaying "in-review camps" in drop-down but restricting selection from front-end if camps are in review because of "parent-child"  change event. so that it doesn't go in loop and tree appears eveytime

while verifying this ticket please verify ticket below as well:
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/158

@vikasranatalentelgia  please implement the front-end checks for the same

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
