### ISSUE TITLE
Old Data : Issue with field "Camp About URL" on camp history page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#281]
Please refer below link : 

https://canonizer3.canonizer.com/camp/history/173-Software-Testing/3-Levels-Of-Testing
Click on below link 

![image](https://user-images.githubusercontent.com/40416610/233172719-d49b979c-1a50-414c-b146-e47476097e39.png)

Getting below results : 
![image](https://user-images.githubusercontent.com/40416610/233173083-99e9441d-af6e-4af5-9869-779a15b39df5.png)

When I click on "Create New Camp ", getting below errors : 
![image](https://user-images.githubusercontent.com/40416610/233173212-e6b1c6ce-655a-48ee-a198-92dd47ddd6ec.png)

**Comment by nalwa** [comment]
@rupalichavan9860  i did debugging on this issue and as per findings in "**_camp_about_url_**" there is plan text entered for this camp. In order to restrict such cases i have below suggestions :

1. Plan text should not be accepted in camp_about_URL while entering URL there should be validation on it.  Not sure if that is implemented now or not, You can verify that.
2. in order to restrict already entered URL  there should also a check in front-end that if its not a URL it should not be displayed there.

For above provided suggestion we  need to discuss it with all teams members and then we can proceed further as per final solution.

below is screenshot of camp_about_url  for this camp:

![Screenshot from 2023-05-30 14-03-56](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/4891200/45c77c05-026b-4611-b261-264467e7660b)

**Comment by rohit-talentelgia** [comment]
@vikasranatalentelgia 

Implement checks on frontend as below:

1. While entering data in Camp About URL, check for Valid URLs only
2. On the history page, where we are showing the Cam About URL, is plain text is coming from API, then do not show the content. Only Valid URLs should be displayed.

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia Working fine on the history page, but the topic detail page also requires the same change.
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/b436bc5a-5f10-437d-a2db-9dcb2d8137a6)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
