### ISSUE TITLE
Emails : We have to replace the forward slash (/) with arrow (>) in all the breadcrumbs throughout the application

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#388]
This is not working for few emails . Please refer below emails 
1.Nickname has removed their delegated support from Topic Name
![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/40416610/08770f75-ed45-4f8c-bb66-fdf6b9bb17e8)

2. Proposed change to Topic Name >> Camp name submitted
![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/40416610/1b6ed316-d010-4290-8f5a-61fa7cc2a388)

3. Proposed change to statement for camp Topic name >> camp name submitted
![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/40416610/9b75eb25-3cdf-44b8-9223-740c8bf3a269)

4. nick name has added their support to Topic name >> camp name. 
![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/40416610/4e0be683-3519-4dbd-86cd-01c60a690a6b)

5.  Nick name has objected to your proposed change.
![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/40416610/4d6dcf41-cf93-47d1-85bc-0f4e055719ae)

**Comment by rupalichavan9860** [comment]
Still facing this issue on live

**Comment by ashish76** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/23633446/83eada23-a8a1-4af8-aff5-caac0711a4a8)
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/23633446/05fd8330-45cc-4d1b-a1ab-3e654a1a9a92)
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/23633446/eb5cf7ae-2def-4490-bb79-f9466b0deb96)
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/23633446/260a1575-f7a2-439b-9499-9aa808029af2)
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/23633446/4dc73fba-c212-49b9-b9af-35ead42ed5ff)
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/23633446/4730390b-90b2-41a4-a1e3-599dfcaa412c)

@rupalichavan9860 On last Thursday, we coordinated with Ashutosh to find out about this issue on production. We found that the email queues were not started and because of that, we are always getting the last cached email version. When we restart the queues and check, everything was working as expected. After getting your comment on this issue, we have re-verified it once again. And it is working fine. Please check the attached screenshots for your reference.

Thanks & Regards
Ashish

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
@ashish76 I am still facing this issue for few emails **on live** . Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/ce61b8d7-0cee-4afd-a4ec-45c175d89f7d)

Do we need to restart the queues?

**Comment by rupalichavan9860** [comment]
@ashish76 Need to check this as not working on live

**Comment by ashish76** [comment]
@rupalichavan9860 Can you check this issue once again?

**Comment by rupalichavan9860** [comment]
@ashish76 This is still not working on live
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/8ea8356e-a800-4de1-be57-f037366a592d)

**Comment by ashish76** [comment]
@rupalichavan9860 we need to discuss this issue with you, let me know what time will be suitable for you.

**Comment by ks-rahul** [comment]
issue has been discussed with Rupali and this is working fine.

**Comment by rupalichavan9860** [comment]
Working fine on live

**Comment by rupalichavan9860** [comment]
Verified on live
