### ISSUE TITLE
Live : Topics are not listing on home page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#468]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/863d7a62-40ad-4b75-8115-6f195d6c2582)

On reload ,it is working fine

**Comment by sajid315** [comment]
@rupalichavan9860 this issue is fixed , basically the cron job was not working to remove non latest trees. We will observe the cron

Issue was "502 Bad Gateway" that mostly occurs when processing overloads or take time for execution. 

Regarding this I will further proceed to check and make the impact analysis about behavior of cache when having multiple version and multiple camps in cache. After that we can identify the performance and latency issues on some observations.

**Comment by rupalichavan9860** [comment]
Verified on live and working fine
