### ISSUE TITLE
Browse Page : When a user changes a Canon, the Canon value displayed in the URL is the ID for a few Canons and the name for a few Canons. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#488]
Please refer attached screenshot : 
General : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/44f32805-16cf-4081-96e8-8b0726872a90)

family > Jesperson_Oscar_F : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/3c28c533-9c90-47f9-b30b-27a0bb7b31fe)

**Comment by ks-rahul** [comment]
The acceptance criteria for this ticket are as follows:

1. When making changes, The Canon ID will be included in the URL instead of the Canon name.
2. Available canon ID in URL will be selected in the dropdown.


@rupalichavan9860 Please review the following acceptance criteria and add any that may be missing.

**Comment by subhancd** [comment]
@rupalichavan9860 canon ID are displayed for all canons.

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by hassaanCD** [comment]
Verified on production
