### ISSUE TITLE
Getting error "Cannot read properties of undefined (reading 'data')" on selecting "Mind Experts" and "Computer Science Experts" for specific topic

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#61]
Getting below error : 
For topic : https://beta.canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement
![image](https://user-images.githubusercontent.com/40416610/205584060-840a383d-2179-4cff-b931-7f211c734bac.png)

**Comment by akuks** [comment]
The error is due the API's taking more than 30 seconds to compute the score.
Following are the API's:

- https://beta-api3.canonizer.com/api/v3/camp-total-support-score
- https://beta-api3.canonizer.com/api/v3/support-and-score-count

This issue is not for all the Topics, it's only for big topics like "Theories of Consciousness"

**Comment by rupalichavan9860** [comment]
@nalwa Sill getting error on beta : 
![image](https://user-images.githubusercontent.com/40416610/208033393-b9af572a-9652-4138-ae56-2f0408dadaad.png)

I'm not getting any errors on staging, but the page is taking a long time to load, so I'm reverting this ticket.

**Comment by rupalichavan9860** [comment]
working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
