### ISSUE TITLE
As of Date filter is not working in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#610]
Steps to reproduce : 
1. Open any topic
2. Apply "As of Date" as any previous date than topic created date 
3. Click on Browse 
4. Observe result 

Actual Result : Topics are not listing 

Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/4668cab2-2a46-4b3e-82be-136871886008)

**Comment by sajid315** [comment]
@rupalichavan9860 I have looked into this issue so the issue was due to no code merge on development server. 
And the issue was coming on development server as well like production. 

So After code merge by Ashutosh its resolved now on development server. For production server it can be by **hotfix** OR we need to wait for next release. Let me know about it. 


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/3b3d3823-d408-4856-9930-a361c86ba74e)

**Comment by rupalichavan9860** [comment]
@sajid315 Thank you for the updates. Let us discuss this in the meeting and make a decision.

**Comment by sajid315** [comment]
Sure @rupalichavan9860, 
Also @akashgit77 already written selenium for topic listing on main page and browse page, but he needs to add one more scenario like mentioned in this ticket. So that in future we have this case as well in automation.

@akashgit77 can you please add this scenario in automation as well ? For support you can ping me about it.

**Comment by akashgit77** [comment]
Sure @sajid315

**Comment by rupalichavan9860** [comment]
Working fine on dev server

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by hassaanCD** [comment]
Verified on production
