### ISSUE TITLE
Profile Picture : Uploaded Profile Picture is breaking

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#672]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/35a87ccd-a65c-48cd-83bd-ef507f394b1f)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
@sajid315 Not able to upload profile picture.
![Screenshot 2024-03-15 at 12 29 51 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/c2513e47-cf25-4a14-bc93-2434796ab258)

**Comment by sajid315** [comment]
This issue is already resolved on development server, but due to not merging of PR. That fixing not gone into release. Below is the fixing PR. 
https://github.com/the-canonizer/canonizer-3.0-api/pull/951
https://github.com/the-canonizer/canonizer-3.0-api/pull/957
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1626

**Comment by hassaanCD** [comment]
Working fine on production
