### ISSUE TITLE
When we are switching the tab from "All Threads" to "My Thread" then other's threads are listed in "My Thread" with "Edit Button"

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#719]

**Comment by akashgit77** [comment]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/0157dd29-13cb-4005-84ed-a2b3fa4335c4

**Comment by sajid315** [comment]
@akashgit77 I have checked this issue on development server, its actually not the issue. Because each API is calling separately on base of "TAB Type".
And the backend response is coming correct on base of payload. 
Only Matter is the clicking on Tabs and about it I would suggest that we can disable other tabs on click of one tab until the response came.

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/4ae476d1-cd20-4ba4-b360-c2f1fdfc01a8)



https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/ea4c418e-43dc-45fe-88c9-7b9ceb9af47b

@sajid315 Please look into the video

**Comment by sajid315** [comment]
@wahaj-hafeez as per review from backend side API's returning the data on base of filters. 
As these listing API calls are called from server side rendering so we need to confirm that either we are passing and updating filter values correctly on change of tabs and types of filters. 
Current issue is occurring on dev site.

**Comment by DevAlchemyCD** [comment]
pr  : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1561

**Comment by akashgit77** [comment]
Working fine on the production.
