### ISSUE TITLE
disable "object" button for the archived camp

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#751]
**Steps**
1. create a topic by user A
2. submit a change in the topic by user B
3. object the change by user A
4. archive agreement camp by user A
5. observe the object button

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/1e615399-7202-405e-bec6-8ad6cca4f5e5)

**Comment by saniatg** [comment]
@wahaj-hafeez this issue is not fixed on development. The object button for archived camp is seen and when click on it shows 'topic num is required' refer screenshot
![Screenshot 2024-01-24 at 1 12 15 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/c6f76e8e-9628-4752-8bbf-e422cbc91297)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1504

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
