### ISSUE TITLE
Support : Reason for adding/removing support and Citation Link are not getting saved 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#795]
Steps to reproduce : 
1. Create topic 
2. Create camp 
3. Support camp - Select any reason from drop down and add Citation Link 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/8ad076ac-5443-4c92-9d9e-2cff6dfac262)
4. Click on submit 
5. Click on manage support and observe 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/9317438d-15dc-46f5-be88-2f3c4132b399)

Actual Result : Reason for adding/removing support and Citation Link are blank

**Comment by ashish76** [comment]
@rupalichavan9860 Reason and Citation links are getting saved but we are not showing the previous value deliberately because it is used to capture this information whenever a user Adds or removes support. Previously we were showing this information as a reference in a read-only mode but it has been removed. I don't remember the discussion exactly. So let's discuss this on Thursday with the team.

**Comment by rupalichavan9860** [comment]
Working fine when adding/removing support. I have reported separate ticket for support order change so closing this

**Comment by rupalichavan9860** [comment]
Verified on live
