### ISSUE TITLE
Beta : Camp is not listing under "Canonizer Sorted Camp Tree"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#82]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/206652595-b160562d-7bdc-43f5-92ae-f6852f70be63.png)

"camp 11" is not listing under tree 
![image](https://user-images.githubusercontent.com/40416610/206652752-134b2b2d-3ae7-4f62-97b7-b5fd58c824a5.png)

and when user click on "camp 11", tree is blank
![image](https://user-images.githubusercontent.com/40416610/206652859-a5e77d86-aee8-4bf7-9076-f334cad3fc7f.png)

**Comment by sajid315** [comment]
@rupalichavan9860 i have verified this issue that is based on old data in database. This topic is old and issue solved in this below ticket.
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/158 
So due to old & non-reproducible issue we can skip it. 
If you found any further cases in future then you can mention.

**Comment by rupalichavan9860** [comment]
As this is data issue ,for time being closing this ticket
