### ISSUE TITLE
Showing topic creating date on default selected filter on Consensus tree when creating new topic 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#953]
![Screenshot 2024-05-03 at 1 17 56 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/8cee1adb-91fa-45de-867f-f2d68e4d2c96)

**Comment by sajid315** [comment]
@wahaj-hafeez I have investigated about this issue and following are my findings:
1- This issue is not persistent issue for all users but only for those who have wrong date & time for system.
2- When a user apply as_of_date filter it passes  time as epoch. 
3- At the same time when he creates topic , the topic is saving at real server time on which we deployed the canonizer. 
4- But after topic creation while getting tree from backend , user system epoch time is passing in API. So regarding we have to add some check for users or some kind of info for users to recheck their machine time.

We need to discuss on this.

**Comment by sajid315** [comment]
@saniatg following are the PR's raised for the fixing of this issue, you can check it with @hassaanCD as well after merge of both of below PR's.
https://github.com/the-canonizer/canonizer-service/pull/317
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1756

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
