### ISSUE TITLE
When we are going to "Eventline" from "Camp History Page" then it keeps loading.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#956]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/bb11cab6-e4f2-464c-9174-5c71e5dda8de

**Comment by saniatg** [comment]
Need to disable eventline from URL now, as button is enabled

**Comment by saniatg** [comment]
@wahaj-hafeez 
Please ignore above comment
The issue here that needs to be fixed is that when we ar eon camp history page, and replace 'camp' with 'eventline' in the URL, the eventline keeps loading.

As discussed , eventline can only be replaced  in topic detail page, if user is going through any other page , it must show 404

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1760

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
